# General
action_space: 3
obs_shape: 9
lr: 0.001
num-env-steps: 1000000
train_freq: 500  # It has to be a multiple of num_steps
num-steps: 250
seed: 5
max_memory_len: 5000
log_interval_episodes: 10

# PPO
clip_param: 0.1
value-loss-coef: 0.5
num-mini-batch: 4
use-linear-lr-decay: True
entropy-coef: 0.01
use_gae: True
gae_lambda: 0.95
num-processes: 4

# DDPG
batch_size: 128
gamma: 0.99
tau: 0.001
