action_space: 3
obs_shape: 9

clip_param: 0.1
lr: 2.5e-4
value-loss-coef: 0.5
num-steps: 2000
num-env-steps: 1000000
num-mini-batch: 4
use-linear-lr-decay: True
entropy-coef: 0.01
train_freq: 128

log-interval: 1
num-processes: 4
use_gae: True
gae_lambda: 0.95
seed: 5
max_memory_len: 10000
