# General
action_space: 2
obs_shape: 5  # 5 or 6, add vz
num_env_episodes: 6009  # Keep it a multiple of evaluate_freq and add evaluate_ep at the end
train_freq: 1  # In episodes
num-steps: 350
seed: 5
max_memory_len: 17500  # 50 episodes
mem_to_use: 4096  # Try to keep this a multiple of the batch size
log_interval_episodes: 100
max_height: 3.5
max_side: 5.0
max_vel_z: 1.0
max_vel_xy: 1.0
train_window_reward: 100
test_window_reward: 3
evaluate_freq: 500
evaluate_ep: 9  # Keep this a multiple of test_window_reward
eval_noise: 0.2  # std for gaussian evaluation noise
model: "paper"  # "paper" or "small"

# DDPG
epochs: 1
batch_size: 64
gamma: 0.99
tau: 0.001
lr_actor: 0.0001
lr_critic: 0.001
