# General
action_space: 2
obs_shape: 5
num_env_episodes: 6000
train_freq: 1  # In episodes
num-steps: 500
seed: 5
max_memory_len: 3000
mem_to_use: 1024  # Try to keep this a multiple of the batch size
log_interval_episodes: 100
max_height: 3.0
max_side: 5.0
max_vel_z: 1.0
max_vel_xy: 1.0
train_window_reward: 100
test_window_reward: 3
evaluate_freq: 500
evaluate_ep: 10

# DDPG
epochs: 1
batch_size: 64
gamma: 0.99
tau: 0.001
lr_actor: 0.0001
lr_critic: 0.001
